// <auto-generated />
namespace ReadLater.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Create_NN_Bookmark_Account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_NN_Bookmark_Account));
        
        string IMigrationMetadata.Id
        {
            get { return "201905231928528_Create_NN_Bookmark_Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
